# Generated by Django 4.2.7 on 2023-12-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='text_color',
            field=models.CharField(default='#000000', help_text='Enter a hex color code for the text', max_length=7),
        ),
        migrations.AddField(
            model_name='status',
            name='title_color',
            field=models.CharField(default='#fff', help_text='Enter a hex color code for the title', max_length=7),
        ),
    ]
