# Generated by Django 4.2.7 on 2023-12-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_status_description_alter_status_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='title_color',
            field=models.CharField(blank=True, default='#000000', help_text='Enter a hex color code for the title', max_length=7),
        ),
    ]
